[package]
name = "spaceism"
version = "0.1.0"
authors = ["gregor"]
edition = "2018"

[dependencies]
bevy = "0.3"
bevy_contrib_bobox = {git = "https://github.com/Bobox214/bevy_contrib_bobox", tag="0.3.0" , features = ["rapier2d"]}
bevy_prototype_lyon = "0.1"
bevy_rapier2d = "0.5"
rapier2d = "0.3"
